### PR TITLE
Fix #28 - add xib support

### LINKED ISSUE #28: Support XIB files
Hey, is it possible to use SBConstants to extract identifiers from .xib files?

It seems like it skips those, but I have lots of them for custom UITableViewCells and would love to use generated constants in my code.

### PR DESCRIPTION
**Pull request by paulsamuels**
I'm not sure if this will cause any issue. I don't think it should be behind a feature switch as it seems like something that should just be default behaviour.

@tp does this resolve your issue?

### CODE REVIEW

**Comment by tp** [comment]
Thanks! The generated file looks good.

Just tried it with `gem specific_install https://github.com/paulsamuels/SBConstants hotfix-28-add-xib-support`, now I will switch some code to constants and give final feedback.

**Comment by tp** [comment]
Great, so this works :-)

But I always have to append `.rawValue` to the enum value. I guess that is a Swift issue though.. Wondering if there is a better way to represent the constants in code.

```swift
let cell = tableView.dequeueReusableCellWithIdentifier(TableViewCellreuseIdentifier.amenitiesListCell.rawValue) as! AmenitiesListCell
```

**Comment by tonyarnold** [comment]
@tp if the tool output structs with static properties instead of enums, the `.rawValue` would be unnecessary:

```swift
public enum SegueIdentifier : String {
    case PSBMasterToDetail = "PSBMasterToDetail"
    case PSBMasterToSettings = "PSBMasterToSettings"
}

var ident = SegueIdentifier.PSBMasterToDetail.rawValue
```

Becomes:

```swift
public struct SegueIdentifier {
    static var PSBMasterToDetail = "PSBMasterToDetail"
    static var PSBMasterToSettings = "PSBMasterToSettings"
}

var ident = SegueIdentifier.PSBMasterToDetail
```

You can probably just update your local templates for now if that's a more attractive option.

**Comment by orta** [comment]
@tonyarnold I thought about that when adding swift support: https://github.com/paulsamuels/SBConstants/pull/26

**Comment by tonyarnold** [comment]
Great to see the discussion has been had — is there some method of shortening out the `.rawValue`? It's ugly as hell and the common use case is to use these in comparisons with strings.

**Comment by orta** [comment]
Yes, see this quote from @ashfurrow 

> We [use this abstraction](https://github.com/artsy/eidolon/blob/49385ffa132fc3a7b8c98f5a61ef8137f3a10b05/Kiosk/App/UIViewControllerExtensions.swift#L14-L16) when invoking segues and [this one](https://github.com/artsy/eidolon/blob/master/Kiosk/App/UIStoryboardSegueExtensions.swift#L6) when comparing them to avoid calling `.rawValue`.

**Comment by tonyarnold** [comment]
Nice. Definitely worth writing those up somewhere.

**Comment by paulsamuels** [comment]
@orta seems as this is just a PR have you got any objections to me undoing that merge as it makes the history ugly. A rebase would prob work nicer

**Comment by orta** [comment]
Sure, I have no problems with that

**Comment by orta** [comment]
This looks good to me then :+1: - merge when you're ready

**Pull request merged**
